In [1]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
import pandas as pd

In [4]:
df=pd.DataFrame(iris.data, columns=iris.feature_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
df['target']=iris.target

In [10]:
df[47:55]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target  
47       0  
48       0  
49       0  
50       1  
51       1  
52       1  
53       1  
54       1

In [25]:
from sklearn.model_selection import train_test_split
import numpy as np

In [12]:
x_train, x_test, y_train, y_test=train_test_split(iris.data, iris.target, test_size=0.3)

In [16]:
from sklearn.svm import SVC
svm=SVC(kernel='rbf', C=30, gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9777777777777777

In [17]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [22]:
cross_val_score(SVC(kernel='linear', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [23]:
cross_val_score(SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [27]:
kernels=['rbf', 'linear']
C=[1, 10, 20]
avg_scores={}
for kval in kernels:
    for cval in C:
        avg_scores[kval+'_'+str(cval)]=np.average(cross_val_score(SVC(kernel=kval, C=cval, gamma='auto'), iris.data, iris.target, cv=5))

avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [29]:
from sklearn.model_selection import GridSearchCV

In [32]:
clf=GridSearchCV(SVC(gamma='auto'),{'C':[1,10,20], 'kernel':['rbf', 'linear']}, cv=5, return_train_score=False)

In [34]:
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00179863, 0.00099936, 0.00100079, 0.00099897, 0.00119653,
        0.00059943]),
 'std_fit_time': array([3.99351419e-04, 5.56082906e-07, 6.32035819e-04, 1.34024327e-06,
        4.00284065e-04, 4.89443494e-04]),
 'mean_score_time': array([0.0009995 , 0.00099998, 0.00060024, 0.00020013, 0.        ,
        0.00059981]),
 'std_score_time': array([1.66824872e-06, 5.91739352e-07, 4.90096112e-04, 4.00257111e-04,
        0.00000000e+00, 4.89746081e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [35]:
df=pd.DataFrame(clf.cv_results_)

In [36]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001799  3.993514e-04         0.000999    1.668249e-06       1   
1       0.000999  5.560829e-07         0.001000    5.917394e-07       1   
2       0.001001  6.320358e-04         0.000600    4.900961e-04      10   
3       0.000999  1.340243e-06         0.000200    4.002571e-04      10   
4       0.001197  4.002841e-04         0.000000    0.000000e+00      20   
5       0.000599  4.894435e-04         0.000600    4.897461e-04      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                5

In [37]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [38]:
clf.best_score_

0.98

In [39]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [41]:
from sklearn.model_selection import RandomizedSearchCV
rf=RandomizedSearchCV(SVC(gamma='auto'),{'C':[1,10,20], 'kernel':['rbf', 'linear']}, cv=5, return_train_score=False, n_iter=2)

In [43]:
rf.fit(iris.data, iris.target)

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
                   estimator=SVC(C=1.0, cache_size=200, class_weight=None,
                                 coef0=0.0, decision_function_shape='ovr',
                                 degree=3, gamma='auto', kernel='rbf',
                                 max_iter=-1, probability=False,
                                 random_state=None, shrinking=True, tol=0.001,
                                 verbose=False),
                   iid='warn', n_iter=2, n_jobs=None,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [44]:
df2=pd.DataFrame(rf.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

In [45]:
df2

param_C param_kernel  mean_test_score
0       1       linear             0.98
1      10          rbf             0.98

In [46]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [48]:
model_params={'svm':{'model': SVC(gamma='auto'),
                    'params':{
                        'C':[1,10,20],
                        'kernel':['rbf', 'linear']
                    }
                }, 
              'random_forest':{
                  'model': RandomForestClassifier(),
                    'params':{
                        'n_estimators':[1,5,10]
                    }
              }, 
              'logistic_regression':{
                  'model': LogisticRegression(solver='liblinear', multi_class='auto'),
                    'params':{
                        'C':[1,5,10]
                    }
              }
        }

In [51]:
scores=[]

for model_name, mp in model_params.items():
    clf=GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })

In [52]:
df3=pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df3

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.966667        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}